version: '2'
services:
  db:
    image: mysql:5.7
    volumes:
      - ./tmp/db/mysql:/var/lib/mysql
    ports:
      - 3308:3306
    environment:
      - "MYSQL_ROOT_PASSWORD=ruby"
      - "MYSQL_PASSWORD=ruby"
      - "MYSQL_DATABASE=clinic"
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/interview
    ports:
      - "3000:3000"
    depends_on:
      - db
